name: Lint and Test
on: push

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13", "3.14"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
        cache-dependency-path: requirements.txt
        allow-prereleases: true
    - run: pip install -r requirements.txt
    - run: ruff check marimo_scipy_utils
    - run: ty check marimo_scipy_utils
    - run: black --check marimo_scipy_utils
